sleep 90 | tr -d '\r'
pip install --upgrade pip | tr -d '\r'
pip install -r requirements.txt | tr -d '\r'
spark-submit --master local[2] --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.0 LoadingExchangeRateDataToDWH.py | tr -d '\r'
spark-submit --master local[2] --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.0 LoadingSymbolDataToDWH.py | tr -d '\r'